//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiOU.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Users
    {
        public int User_Id { get; set; }
        public bool IsWebMaster { get; set; }
        public string Description { get; set; }
        public bool IsSuperAdmin { get; set; }
        public long Created { get; set; }
        public int CreayedBy { get; set; }
        public long Updated { get; set; }
        public int UpdatedBy { get; set; }
    }
}
