//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiOU.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public sbyte Level { get; set; }
        public int Upid { get; set; }
        public short List { get; set; }
        public int Order { get; set; }
        public bool IsDirect { get; set; }
    }
}
