//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiOU.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public int ProductId { get; set; }
        public int PriceCategory { get; set; }
        public int PriceId { get; set; }
        public int PayType { get; set; }
        public int Status { get; set; }
        public long Created { get; set; }
        public int UserId { get; set; }
        public long Updated { get; set; }
        public int UpdatedUserId { get; set; }
        public string Description { get; set; }
        public long StartTime { get; set; }
        public long EndTime { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public bool ExtendApplied { get; set; }
        public long ExtendTime { get; set; }
        public long ExtendEndTime { get; set; }
        public int ExtendApproved { get; set; }
        public string ExtendRejectedMessage { get; set; }
    }
}
