//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiOU.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaintenance
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int MaintenanceType { get; set; }
        public long Created { get; set; }
        public string Description { get; set; }
        public long Finished { get; set; }
        public long Updated { get; set; }
    }
}
