//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiOU.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Email { get; set; }
        public int ExternalUserType { get; set; }
        public string ExternalUserId { get; set; }
        public string Password { get; set; }
        public int Gendar { get; set; }
        public long RegTime { get; set; }
        public long Updated { get; set; }
        public int UserType { get; set; }
        public int VipLevel { get; set; }
        public int Province { get; set; }
        public int City { get; set; }
        public int District { get; set; }
        public string Location { get; set; }
        public string XPlot { get; set; }
        public string YPlot { get; set; }
    }
}
